// Generated by `rig add --rust crc32fast` (see the README).
import { crc32fast_abi_version, crc32fast_hash } from "./rig_bindings/crc32fast";

const text = new TextEncoder().encode("hello");
const crc = crc32fast_hash(text);
console.log("ts-host-crc32fast: crc32fast abi=", crc32fast_abi_version(), "crc32(hello)=", crc);
if (crc !== 907060870) {
  throw new Error("unexpected crc32");
}
