//! C/C++ host ← cargo package via generic C ABI façade.

use crate::manifest::Dependency;
use anyhow::{Context, Result};
use std::path::Path;

/// Write a C header wrapping the façade discovery surface + link metadata.
pub fn write_c_bindings(
    out: &Path,
    name: &str,
    dep: &Dependency,
    header: Option<&Path>,
    lib_name: &str,
    native_dir: &str,
) -> Result<()> {
    let ver = dep.version.as_deref().unwrap_or("*");
    let safe = name.replace('-', "_");
    let guard = format!("RIG_{}_HOST_H", safe.to_uppercase());

    let mut body = String::new();
    body.push_str(&format!(
        "/* Auto-generated by rig for cargo package `{name}` ({ver}).\n\
         * Link: -L{native_dir} -l{lib_name}  (and rpath as needed)\n\
         * Do not edit — regenerate with `rig sync` / `rig add`.\n\
         */\n\
         #ifndef {guard}\n\
         #define {guard}\n\
         #include <stdint.h>\n\
         \n\
         #ifdef __cplusplus\n\
         extern \"C\" {{\n\
         #endif\n\n"
    ));

    if let Some(header) = header.filter(|h| h.is_file()) {
        if let Some(fname) = header.file_name().and_then(|s| s.to_str()) {
            body.push_str(&format!(
                "/* Façade header (copied beside this file when possible): {fname} */\n\
                 #include \"{fname}\"\n\n"
            ));
        }
    } else {
        body.push_str(&format!(
            "uint32_t {safe}_abi_version(void);\n\
             const char *{safe}_version(void);\n\
             const char *{safe}_name(void);\n\n"
        ));
    }

    body.push_str(&format!(
        "#ifndef RIG_HOST_META_{safe}\n\
         #define RIG_HOST_META_{safe}\n\
         #define RIG_PACKAGE_NAME_{safe} \"{name}\"\n\
         #define RIG_PACKAGE_VERSION_{safe} \"{ver}\"\n\
         #define RIG_NATIVE_LIB_{safe} \"{lib_name}\"\n\
         #define RIG_NATIVE_DIR_{safe} \"{native_dir}\"\n\
         #endif\n\n\
         #ifdef __cplusplus\n\
         }}\n\
         #endif\n\
         \n\
         #endif /* {guard} */\n"
    ));

    std::fs::write(out, body).with_context(|| format!("write {}", out.display()))?;
    Ok(())
}

/// Path/git stub for C hosts — documents the pin and expected manual link.
pub fn write_c_path_git_stub(out: &Path, name: &str, dep: &Dependency) -> Result<()> {
    let safe = name.replace('-', "_");
    let load = dep
        .path
        .clone()
        .or_else(|| dep.git.clone())
        .or_else(|| dep.url.clone())
        .unwrap_or_else(|| format!("vendor/{name}"));
    let body = format!(
        "/* Auto-generated by rig — C host ← {eco} `{name}` (path/git).\n\
         * No cargo cdylib façade. Link `{load}` (or its built artifact) yourself.\n\
         */\n\
         #ifndef RIG_{guard}_PATH_H\n\
         #define RIG_{guard}_PATH_H\n\
         #define RIG_LOAD_PATH_{safe} \"{load}\"\n\
         #endif\n",
        eco = dep.ecosystem,
        guard = safe.to_uppercase(),
    );
    std::fs::write(out, body).with_context(|| format!("write {}", out.display()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::manifest::Dependency;

    fn dep(version: &str) -> Dependency {
        Dependency {
            ecosystem: "cargo".into(),
            version: Some(version.into()),
            git: None,
            rev: None,
            path: None,
            url: None,
            features: None,
            default_features: None,
            expose: true,
            expose_opts: None,
        }
    }

    #[test]
    fn c_bindings_include_link_meta() {
        let dir = tempfile::tempdir().unwrap();
        let out = dir.path().join("sha2.h");
        write_c_bindings(
            &out,
            "sha2",
            &dep("0.10.9"),
            None,
            "sha2_ffi",
            "target/rig/sha2",
        )
        .unwrap();
        let text = std::fs::read_to_string(&out).unwrap();
        assert!(text.contains("sha2_abi_version"));
        assert!(text.contains("RIG_NATIVE_LIB_sha2"));
        assert!(text.contains("sha2_ffi"));
    }
}
