//! C# host ← cargo package via generic C ABI façade (P/Invoke).

use crate::expose::api_scan::ExportFn;
use crate::expose::surface;
use crate::manifest::Dependency;
use anyhow::{Context, Result};
use std::path::Path;

/// Emit a C# partial class with DllImport for façade markers (+ scanned exports).
pub fn write_csharp_bindings(
    out: &Path,
    name: &str,
    dep: &Dependency,
    lib_name: &str,
    native_dir: &str,
    exports: &[ExportFn],
) -> Result<()> {
    let ver = dep.version.as_deref().unwrap_or("*");
    let safe = name.replace('-', "_");
    let class = format!("{}Native", to_pascal(&safe));
    let mut body = String::new();
    body.push_str(&format!(
        "// Auto-generated by rig for cargo package `{name}` ({ver}).\n\
         // Native lib: {lib_name} (search hint: {native_dir})\n\
         // Do not edit — regenerate with `rig sync` / `rig add`.\n\
         using System;\n\
         using System.Runtime.InteropServices;\n\
         \n\
         public static class {class}\n\
         {{\n\
             public const string PackageName = \"{name}\";\n\
             public const string PackageVersion = \"{ver}\";\n\
             public const string NativeLib = \"{lib_name}\";\n\
             public const string NativeDir = \"{native_dir}\";\n"
    ));

    if exports.is_empty() {
        body.push_str(&format!(
            "\n\
             [DllImport(\"{lib_name}\", CallingConvention = CallingConvention.Cdecl)]\n\
             public static extern uint {safe}_abi_version();\n\
         \n\
             [DllImport(\"{lib_name}\", CallingConvention = CallingConvention.Cdecl)]\n\
             public static extern IntPtr {safe}_version();\n\
         \n\
             [DllImport(\"{lib_name}\", CallingConvention = CallingConvention.Cdecl)]\n\
             public static extern IntPtr {safe}_name();\n"
        ));
    } else {
        body.push_str(&surface::emit_csharp_dllimports(exports, lib_name));
    }

    body.push_str(&format!(
        "\n\
             public static string VersionString() =>\n\
                 Marshal.PtrToStringUTF8({safe}_version()) ?? string.Empty;\n\
         \n\
             public static string NameString() =>\n\
                 Marshal.PtrToStringUTF8({safe}_name()) ?? string.Empty;\n"
    ));

    if exports.iter().any(|e| e.export_name == "sha2_hash_256") {
        body.push_str(
            "\n\
             public static byte[] Hash256(byte[] data)\n\
             {\n\
                 var output = new byte[32];\n\
                 var rc = sha2_hash_256(data, (UIntPtr)data.Length, output);\n\
                 if (rc != 0) throw new InvalidOperationException($\"sha2_hash_256 failed: {rc}\");\n\
                 return output;\n\
             }\n",
        );
    }
    if exports.iter().any(|e| e.export_name == "sha2_hash_512") {
        body.push_str(
            "\n\
             public static byte[] Hash512(byte[] data)\n\
             {\n\
                 var output = new byte[64];\n\
                 var rc = sha2_hash_512(data, (UIntPtr)data.Length, output);\n\
                 if (rc != 0) throw new InvalidOperationException($\"sha2_hash_512 failed: {rc}\");\n\
                 return output;\n\
             }\n",
        );
    }

    if exports.iter().any(|e| e.export_name == "crc32fast_hash") {
        body.push_str(
            "\n\
             public static uint Crc32(byte[] data) =>\n\
                 crc32fast_hash(data, (UIntPtr)data.Length);\n",
        );
    }

    body.push_str("}\n");
    std::fs::write(out, body).with_context(|| format!("write {}", out.display()))?;
    Ok(())
}

fn to_pascal(s: &str) -> String {
    s.split('_')
        .filter(|p| !p.is_empty())
        .map(|p| {
            let mut c = p.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
            }
        })
        .collect()
}

/// Bindings for a built path/git native lib on a C# host (P/Invoke).
pub fn write_csharp_path_native(
    out: &Path,
    name: &str,
    dep: &Dependency,
    built: &crate::expose::path_native::PathNativeBuild,
) -> Result<()> {
    let safe = name.replace('-', "_");
    let class = format!("{}Native", to_pascal(&safe));
    let meta = crate::expose::path_native::path_native_meta_comment(name, dep, built);
    let mut exports = crate::expose::c_header_scan::scan_headers(&built.headers);
    if dep.ecosystem == "zig" {
        for e in crate::expose::zig_export_scan::scan_zig_sources(&built.source_root) {
            if !exports.iter().any(|x| x.export_name == e.export_name) {
                exports.push(e);
            }
        }
    }
    let mut body = format!(
        "// Auto-generated by rig — {meta}\n\
         // Do not edit — regenerate with `rig sync` / `rig add`.\n\
         using System;\n\
         using System.Runtime.InteropServices;\n\
         \n\
         public static class {class}\n\
         {{\n\
             public const string PackageName = \"{name}\";\n\
             public const string NativeLib = \"{lib}\";\n\
             public const string NativeDir = \"{dir}\";\n\
             public const string SourceRoot = \"{src}\";\n",
        lib = built.lib_name,
        dir = built.native_rel,
        src = built.source_root.display(),
    );
    if exports.is_empty() {
        body.push_str(
            "\n             // Add [DllImport] decls for exported C symbols discovered in headers.\n",
        );
    } else {
        body.push_str(&surface::emit_csharp_dllimports(&exports, &built.lib_name));
    }
    body.push_str("}\n");
    std::fs::write(out, body).with_context(|| format!("write {}", out.display()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::expose::api_scan::{ExportFn, ExportKind, FfiType, Param};
    use crate::manifest::Dependency;

    fn dep(version: &str) -> Dependency {
        Dependency {
            ecosystem: "cargo".into(),
            version: Some(version.into()),
            git: None,
            rev: None,
            path: None,
            url: None,
            features: None,
            default_features: None,
            expose: true,
            expose_opts: None,
        }
    }

    #[test]
    fn csharp_bindings_emit_dllimport() {
        let dir = tempfile::tempdir().unwrap();
        let out = dir.path().join("Sha2.cs");
        let exports = vec![
            ExportFn {
                export_name: "sha2_abi_version".into(),
                rust_callee: None,
                params: vec![],
                ret: FfiType::U32,
                ret_adapt: Default::default(),
                kind: ExportKind::Marker,
                is_unsafe: false,
            },
            ExportFn {
                export_name: "sha2_version".into(),
                rust_callee: None,
                params: vec![],
                ret: FfiType::ConstCChar,
                ret_adapt: Default::default(),
                kind: ExportKind::Marker,
                is_unsafe: false,
            },
            ExportFn {
                export_name: "sha2_name".into(),
                rust_callee: None,
                params: vec![],
                ret: FfiType::ConstCChar,
                ret_adapt: Default::default(),
                kind: ExportKind::Marker,
                is_unsafe: false,
            },
            ExportFn {
                export_name: "sha2_hash_256".into(),
                rust_callee: None,
                params: vec![
                    Param {
                        name: "data".into(),
                        ty: FfiType::ConstPtr(Box::new(FfiType::U8)),
                        adapt: Default::default(),
                    },
                    Param {
                        name: "len".into(),
                        ty: FfiType::Usize,
                        adapt: Default::default(),
                    },
                    Param {
                        name: "output".into(),
                        ty: FfiType::MutPtr(Box::new(FfiType::U8)),
                        adapt: Default::default(),
                    },
                ],
                ret: FfiType::I32,
                ret_adapt: Default::default(),
                kind: ExportKind::Enrichment,
                is_unsafe: false,
            },
        ];
        write_csharp_bindings(
            &out,
            "sha2",
            &dep("0.10.9"),
            "sha2_ffi",
            "target/rig/sha2",
            &exports,
        )
        .unwrap();
        let text = std::fs::read_to_string(&out).unwrap();
        assert!(text.contains("DllImport(\"sha2_ffi\""));
        assert!(text.contains("sha2_abi_version"));
        assert!(text.contains("sha2_hash_256"));
        assert!(text.contains("Hash256"));
    }

    #[test]
    fn csharp_path_native_emits_dllimport_from_header() {
        let dir = tempfile::tempdir().unwrap();
        let hdr = dir.path().join("demo.h");
        std::fs::write(&hdr, "int demo_add(int a, int b);\n").unwrap();
        let out = dir.path().join("demo.cs");
        let dep = Dependency {
            ecosystem: "c".into(),
            version: None,
            git: None,
            rev: None,
            path: Some(dir.path().display().to_string()),
            url: None,
            features: None,
            default_features: None,
            expose: true,
            expose_opts: None,
        };
        let built = crate::expose::path_native::PathNativeBuild {
            lib_name: "demo_native".into(),
            native_dir: dir.path().join("target/rig/demo"),
            native_rel: "target/rig/demo".into(),
            lib_path: dir.path().join("target/rig/demo/libdemo_native.so"),
            headers: vec![hdr],
            source_root: dir.path().to_path_buf(),
        };
        write_csharp_path_native(&out, "demo", &dep, &built).unwrap();
        let text = std::fs::read_to_string(&out).unwrap();
        assert!(text.contains("DllImport(\"demo_native\""));
        assert!(text.contains("demo_add"));
        assert!(text.contains("SourceRoot"));
        assert!(text.contains("DemoNative"));
    }
}
