//! D host ← cargo package via generic C ABI façade.

use crate::expose::api_scan::ExportFn;
use crate::expose::surface;
use crate::manifest::Dependency;
use anyhow::{Context, Result};
use std::path::Path;

/// Emit D `extern(C)` declarations + pragma link hints for the façade cdylib.
pub fn write_d_bindings(
    out: &Path,
    name: &str,
    dep: &Dependency,
    lib_name: &str,
    native_dir: &str,
    exports: &[ExportFn],
) -> Result<()> {
    let ver = dep.version.as_deref().unwrap_or("*");
    let safe = name.replace('-', "_");
    let mut body = String::new();
    body.push_str(&format!(
        "// Auto-generated by rig for cargo package `{name}` ({ver}).\n\
         // Link: -L{native_dir} -l{lib_name}\n\
         // Do not edit — regenerate with `rig sync` / `rig add`.\n\
         module rig_bindings.{safe};\n\
         \n\
         pragma(lib, \"{lib_name}\");\n\
         // Add -L{native_dir} on the dmd/ldc command line (or DUB lflags).\n\
         \n\
         extern(C) {{\n"
    ));
    if exports.is_empty() {
        body.push_str(&format!(
            "    uint {safe}_abi_version();\n\
             const(char)* {safe}_version();\n\
             const(char)* {safe}_name();\n"
        ));
    } else {
        body.push_str(&surface::emit_d_externs(exports));
    }
    body.push_str(&format!(
        "}}\n\
         \n\
         enum string packageName = \"{name}\";\n\
         enum string packageVersion = \"{ver}\";\n\
         enum string nativeLib = \"{lib_name}\";\n\
         enum string nativeDir = \"{native_dir}\";\n"
    ));
    std::fs::write(out, body).with_context(|| format!("write {}", out.display()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::expose::api_scan::{ExportFn, ExportKind, FfiType};
    use crate::manifest::Dependency;

    #[test]
    fn d_bindings_emit_extern_c() {
        let dep = Dependency {
            ecosystem: "cargo".into(),
            version: Some("0.10.9".into()),
            git: None,
            rev: None,
            path: None,
            url: None,
            features: None,
            default_features: None,
            expose: true,
            expose_opts: None,
        };
        let dir = tempfile::tempdir().unwrap();
        let out = dir.path().join("sha2.d");
        let exports = vec![
            ExportFn {
                export_name: "sha2_abi_version".into(),
                rust_callee: None,
                params: vec![],
                ret: FfiType::U32,
                kind: ExportKind::Marker,
                is_unsafe: false,
            },
            ExportFn {
                export_name: "sha2_hash_256".into(),
                rust_callee: None,
                params: vec![],
                ret: FfiType::I32,
                kind: ExportKind::Enrichment,
                is_unsafe: false,
            },
        ];
        write_d_bindings(&out, "sha2", &dep, "sha2_ffi", "target/rig/sha2", &exports).unwrap();
        let text = std::fs::read_to_string(&out).unwrap();
        assert!(text.contains("extern(C)"));
        assert!(text.contains("sha2_abi_version"));
        assert!(text.contains("sha2_hash_256"));
        assert!(text.contains("pragma(lib"));
    }
}
