//! D host ← cargo package via generic C ABI façade.

use crate::expose::api_scan::ExportFn;
use crate::expose::surface;
use crate::manifest::Dependency;
use anyhow::{Context, Result};
use std::path::Path;

/// Emit D `extern(C)` declarations + pragma link hints for the façade cdylib.
pub fn write_d_bindings(
    out: &Path,
    name: &str,
    dep: &Dependency,
    lib_name: &str,
    native_dir: &str,
    exports: &[ExportFn],
) -> Result<()> {
    let ver = dep.version.as_deref().unwrap_or("*");
    let safe = name.replace('-', "_");
    let mut body = String::new();
    body.push_str(&format!(
        "// Auto-generated by rig for cargo package `{name}` ({ver}).\n\
         // Link: -L{native_dir} -l{lib_name}\n\
         // Do not edit — regenerate with `rig sync` / `rig add`.\n\
         module rig_bindings.{safe};\n\
         \n\
         pragma(lib, \"{lib_name}\");\n\
         // Add -L{native_dir} on the dmd/ldc command line (or DUB lflags).\n\
         \n\
         extern(C) {{\n"
    ));
    if exports.is_empty() {
        body.push_str(&format!(
            "    uint {safe}_abi_version();\n\
             const(char)* {safe}_version();\n\
             const(char)* {safe}_name();\n"
        ));
    } else {
        body.push_str(&surface::emit_d_externs(exports));
    }
    body.push_str(&format!(
        "}}\n\
         \n\
         enum string packageName = \"{name}\";\n\
         enum string packageVersion = \"{ver}\";\n\
         enum string nativeLib = \"{lib_name}\";\n\
         enum string nativeDir = \"{native_dir}\";\n"
    ));
    std::fs::write(out, body).with_context(|| format!("write {}", out.display()))?;
    Ok(())
}

/// Bindings for a built path/git native lib on a D host.
pub fn write_d_path_native(
    out: &Path,
    name: &str,
    dep: &Dependency,
    built: &crate::expose::path_native::PathNativeBuild,
) -> Result<()> {
    let safe = name.replace('-', "_");
    let meta = crate::expose::path_native::path_native_meta_comment(name, dep, built);
    let mut exports = crate::expose::c_header_scan::scan_headers(&built.headers);
    if dep.ecosystem == "zig" {
        for e in crate::expose::zig_export_scan::scan_zig_sources(&built.source_root) {
            if !exports.iter().any(|x| x.export_name == e.export_name) {
                exports.push(e);
            }
        }
    }
    let mut body = format!(
        "// Auto-generated by rig — {meta}\n\
         // Do not edit — regenerate with `rig sync` / `rig add`.\n\
         // Link: -L{dir} -l{lib}\n\
         module rig_bindings.{safe};\n\
         \n\
         pragma(lib, \"{lib}\");\n\
         // Add -L{dir} on the dmd/ldc command line (or DUB lflags).\n\
         \n\
         extern(C) {{\n",
        dir = built.native_rel,
        lib = built.lib_name,
    );
    if exports.is_empty() {
        body.push_str("    // Add extern(C) decls for exported C symbols discovered in headers.\n");
    } else {
        body.push_str(&surface::emit_d_externs(&exports));
    }
    body.push_str(&format!(
        "}}\n\
         \n\
         enum string packageName = \"{name}\";\n\
         enum string nativeLib = \"{lib}\";\n\
         enum string nativeDir = \"{dir}\";\n\
         enum string sourceRoot = \"{src}\";\n",
        lib = built.lib_name,
        dir = built.native_rel,
        src = built.source_root.display(),
    ));
    std::fs::write(out, body).with_context(|| format!("write {}", out.display()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::expose::api_scan::{ExportFn, ExportKind, FfiType};
    use crate::manifest::Dependency;

    #[test]
    fn d_bindings_emit_extern_c() {
        let dep = Dependency {
            ecosystem: "cargo".into(),
            version: Some("0.10.9".into()),
            git: None,
            rev: None,
            path: None,
            url: None,
            features: None,
            default_features: None,
            expose: true,
            expose_opts: None,
        };
        let dir = tempfile::tempdir().unwrap();
        let out = dir.path().join("sha2.d");
        let exports = vec![
            ExportFn {
                export_name: "sha2_abi_version".into(),
                rust_callee: None,
                params: vec![],
                ret: FfiType::U32,
                ret_adapt: Default::default(),
                kind: ExportKind::Marker,
                is_unsafe: false,
            },
            ExportFn {
                export_name: "sha2_hash_256".into(),
                rust_callee: None,
                params: vec![],
                ret: FfiType::I32,
                ret_adapt: Default::default(),
                kind: ExportKind::Enrichment,
                is_unsafe: false,
            },
        ];
        write_d_bindings(&out, "sha2", &dep, "sha2_ffi", "target/rig/sha2", &exports).unwrap();
        let text = std::fs::read_to_string(&out).unwrap();
        assert!(text.contains("extern(C)"));
        assert!(text.contains("sha2_abi_version"));
        assert!(text.contains("sha2_hash_256"));
        assert!(text.contains("pragma(lib"));
    }

    #[test]
    fn d_path_native_emits_extern_from_header() {
        let dir = tempfile::tempdir().unwrap();
        let hdr = dir.path().join("demo.h");
        std::fs::write(&hdr, "int demo_add(int a, int b);\n").unwrap();
        let out = dir.path().join("demo.d");
        let dep = Dependency {
            ecosystem: "c".into(),
            version: None,
            git: None,
            rev: None,
            path: Some(dir.path().display().to_string()),
            url: None,
            features: None,
            default_features: None,
            expose: true,
            expose_opts: None,
        };
        let built = crate::expose::path_native::PathNativeBuild {
            lib_name: "demo_native".into(),
            native_dir: dir.path().join("target/rig/demo"),
            native_rel: "target/rig/demo".into(),
            lib_path: dir.path().join("target/rig/demo/libdemo_native.so"),
            headers: vec![hdr],
            source_root: dir.path().to_path_buf(),
        };
        write_d_path_native(&out, "demo", &dep, &built).unwrap();
        let text = std::fs::read_to_string(&out).unwrap();
        assert!(text.contains("extern(C)"));
        assert!(text.contains("demo_add"));
        assert!(text.contains("pragma(lib"));
        assert!(text.contains("sourceRoot"));
    }
}
