//! D host ← cargo package via generic C ABI façade.

use crate::manifest::Dependency;
use anyhow::{Context, Result};
use std::path::Path;

/// Emit D `extern(C)` declarations + pragma link hints for the façade cdylib.
pub fn write_d_bindings(
    out: &Path,
    name: &str,
    dep: &Dependency,
    lib_name: &str,
    native_dir: &str,
) -> Result<()> {
    let ver = dep.version.as_deref().unwrap_or("*");
    let safe = name.replace('-', "_");
    let mut body = String::new();
    body.push_str(&format!(
        "// Auto-generated by rig for cargo package `{name}` ({ver}).\n\
         // Link: -L{native_dir} -l{lib_name}\n\
         // Do not edit — regenerate with `rig sync` / `rig add`.\n\
         module rig_bindings.{safe};\n\
         \n\
         pragma(lib, \"{lib_name}\");\n\
         // Add -L{native_dir} on the dmd/ldc command line (or DUB lflags).\n\
         \n\
         extern(C) {{\n\
             uint {safe}_abi_version();\n\
             const(char)* {safe}_version();\n\
             const(char)* {safe}_name();\n"
    ));
    if name == "sha2" {
        body.push_str("    int sha2_hash_256(const(ubyte)* data, size_t len, ubyte* out_);\n");
    }
    if matches!(name, "rx4" | "rotary") {
        body.push_str(
            "    void* rx4_agent_new();\n\
             void rx4_agent_free(void* agent);\n\
             int rx4_prompt_smoke(void* agent, const(char)* prompt);\n",
        );
    }
    body.push_str(&format!(
        "}}\n\
         \n\
         enum string packageName = \"{name}\";\n\
         enum string packageVersion = \"{ver}\";\n\
         enum string nativeLib = \"{lib_name}\";\n\
         enum string nativeDir = \"{native_dir}\";\n"
    ));
    std::fs::write(out, body).with_context(|| format!("write {}", out.display()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::manifest::Dependency;

    #[test]
    fn d_bindings_emit_extern_c() {
        let dep = Dependency {
            ecosystem: "cargo".into(),
            version: Some("0.10.9".into()),
            git: None,
            rev: None,
            path: None,
            url: None,
            features: None,
            default_features: None,
            expose: true,
            expose_opts: None,
        };
        let dir = tempfile::tempdir().unwrap();
        let out = dir.path().join("sha2.d");
        write_d_bindings(&out, "sha2", &dep, "sha2_ffi", "target/rig/sha2").unwrap();
        let text = std::fs::read_to_string(&out).unwrap();
        assert!(text.contains("extern(C)"));
        assert!(text.contains("sha2_abi_version"));
        assert!(text.contains("sha2_hash_256"));
        assert!(text.contains("pragma(lib"));
    }
}
