//! Hare host ← cargo package via generic C ABI façade.

use crate::expose::api_scan::ExportFn;
use crate::expose::surface;
use crate::manifest::Dependency;
use anyhow::{Context, Result};
use std::path::Path;

/// Emit Hare `@symbol` C ABI declarations + link hints for the façade cdylib.
pub fn write_hare_bindings(
    out: &Path,
    name: &str,
    dep: &Dependency,
    lib_name: &str,
    native_dir: &str,
    exports: &[ExportFn],
) -> Result<()> {
    let ver = dep.version.as_deref().unwrap_or("*");
    let safe = name.replace('-', "_");
    let mut body = String::new();
    body.push_str(&format!(
        "// Auto-generated by rig for cargo package `{name}` ({ver}).\n\
         // Link: hare build -L{native_dir} -l{lib_name}\n\
         // Do not edit — regenerate with `rig sync` / `rig add`.\n\
         use types;\n\
         \n\
         // Link hints (passed via hare(1) / ld):\n\
         //   -L{native_dir} -l{lib_name} -Wl,-rpath,{native_dir}\n\
         \n"
    ));
    if exports.is_empty() {
        body.push_str(&format!(
            "export @symbol(\"{safe}_abi_version\") fn {safe}_abi_version() u32;\n\
             export @symbol(\"{safe}_version\") fn {safe}_version() *const char;\n\
             export @symbol(\"{safe}_name\") fn {safe}_name() *const char;\n"
        ));
    } else {
        body.push_str(&surface::emit_hare_fns(exports));
    }
    body.push_str(&format!(
        "\n\
         export const package_name: str = \"{name}\";\n\
         export const package_version: str = \"{ver}\";\n\
         export const native_lib: str = \"{lib_name}\";\n\
         export const native_dir: str = \"{native_dir}\";\n"
    ));
    std::fs::write(out, body).with_context(|| format!("write {}", out.display()))?;
    Ok(())
}

/// Bindings for a built path/git native lib on a Hare host.
pub fn write_hare_path_native(
    out: &Path,
    name: &str,
    dep: &Dependency,
    built: &crate::expose::path_native::PathNativeBuild,
) -> Result<()> {
    let meta = crate::expose::path_native::path_native_meta_comment(name, dep, built);
    let mut exports = crate::expose::c_header_scan::scan_headers(&built.headers);
    if dep.ecosystem == "zig" {
        for e in crate::expose::zig_export_scan::scan_zig_sources(&built.source_root) {
            if !exports.iter().any(|x| x.export_name == e.export_name) {
                exports.push(e);
            }
        }
    }
    let mut body = format!(
        "// Auto-generated by rig — {meta}\n// Do not edit — regenerate with `rig sync` / `rig add`.\n// Link: -L{dir} -l{lib}\n\n",
        dir = built.native_rel,
        lib = built.lib_name,
    );
    if exports.is_empty() {
        body.push_str("// Declare @symbol fn … matching the native C ABI.\n");
    } else {
        body.push_str(&surface::emit_hare_fns(&exports));
        body.push('\n');
    }
    body.push_str(&format!(
        "export const package_name: str = \"{name}\";\nexport const native_lib: str = \"{lib}\";\nexport const native_dir: str = \"{dir}\";\n",
        lib = built.lib_name,
        dir = built.native_rel,
    ));
    std::fs::write(out, body).with_context(|| format!("write {}", out.display()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::expose::api_scan::{ExportFn, ExportKind, FfiType};
    use crate::manifest::Dependency;

    fn dep(version: &str) -> Dependency {
        Dependency {
            ecosystem: "cargo".into(),
            version: Some(version.into()),
            git: None,
            rev: None,
            path: None,
            url: None,
            features: None,
            default_features: None,
            expose: true,
            expose_opts: None,
        }
    }

    #[test]
    fn hare_bindings_emit_symbol() {
        let dir = tempfile::tempdir().unwrap();
        let out = dir.path().join("sha2.ha");
        let exports = vec![
            ExportFn {
                export_name: "sha2_abi_version".into(),
                rust_callee: None,
                params: vec![],
                ret: FfiType::U32,
                ret_adapt: Default::default(),
                kind: ExportKind::Marker,
                is_unsafe: false,
            },
            ExportFn {
                export_name: "sha2_hash_256".into(),
                rust_callee: None,
                params: vec![],
                ret: FfiType::I32,
                ret_adapt: Default::default(),
                kind: ExportKind::Enrichment,
                is_unsafe: false,
            },
        ];
        write_hare_bindings(
            &out,
            "sha2",
            &dep("0.10.9"),
            "sha2_ffi",
            "target/rig/sha2",
            &exports,
        )
        .unwrap();
        let text = std::fs::read_to_string(&out).unwrap();
        assert!(text.contains("@symbol(\"sha2_abi_version\")"));
        assert!(text.contains("sha2_hash_256"));
        assert!(text.contains("-lsha2_ffi"));
    }
}
