//! Nim host ← cargo package via generic C ABI façade.

use crate::expose::api_scan::ExportFn;
use crate::expose::surface;
use crate::manifest::Dependency;
use anyhow::{Context, Result};
use std::path::Path;

/// Write Nim importc bindings that link the façade cdylib via passL.
pub fn write_nim_bindings(
    out: &Path,
    name: &str,
    dep: &Dependency,
    lib_name: &str,
    native_dir: &str,
    exports: &[ExportFn],
) -> Result<()> {
    let ver = dep.version.as_deref().unwrap_or("*");
    let safe = name.replace('-', "_");
    let mut body = String::new();
    body.push_str(&format!(
        "# Auto-generated by rig for cargo package `{name}` ({ver}).\n\
         # Link search: {native_dir}  lib: {lib_name}\n\
         # Do not edit — regenerate with `rig sync` / `rig add`.\n\
         {{.passL: \"-L{native_dir}\".}}\n\
         {{.passL: \"-l{lib_name}\".}}\n\
         {{.passL: \"-Wl,-rpath,{native_dir}\".}}\n\
         \n"
    ));
    if exports.is_empty() {
        body.push_str(&format!(
            "proc {safe}_abi_version*(): cuint {{.importc, cdecl.}}\n\
             proc {safe}_version*(): cstring {{.importc, cdecl.}}\n\
             proc {safe}_name*(): cstring {{.importc, cdecl.}}\n"
        ));
    } else {
        body.push_str(&surface::emit_nim_procs(exports));
    }
    body.push_str(&format!(
        "\n\
         const\n\
           packageName* = \"{name}\"\n\
           packageVersion* = \"{ver}\"\n\
           nativeLib* = \"{lib_name}\"\n\
           nativeDir* = \"{native_dir}\"\n"
    ));

    std::fs::write(out, body).with_context(|| format!("write {}", out.display()))?;
    Ok(())
}

/// Stub for path/git (non-cargo) deps on a Nim host — load-path hint.
pub fn write_nim_path_git_stub(out: &Path, name: &str, dep: &Dependency) -> Result<()> {
    let safe = name.replace('-', "_");
    let load = dep
        .path
        .clone()
        .or_else(|| dep.git.clone())
        .or_else(|| dep.url.clone())
        .unwrap_or_else(|| format!("vendor/{name}"));
    let body = format!(
        "# Auto-generated by rig — Nim host ← {eco} `{name}` (path/git).\n\
         # No cargo cdylib façade; load a native library yourself or point path: at a .so/.dylib.\n\
         const rigLoadPath_{safe}* = \"{load}\"\n\
         # Example: let lib = loadLib(rigLoadPath_{safe})\n",
        eco = dep.ecosystem,
    );
    std::fs::write(out, body).with_context(|| format!("write {}", out.display()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::expose::api_scan::{ExportFn, ExportKind, FfiType};
    use crate::manifest::Dependency;

    fn dep(version: &str) -> Dependency {
        Dependency {
            ecosystem: "cargo".into(),
            version: Some(version.into()),
            git: None,
            rev: None,
            path: None,
            url: None,
            features: None,
            default_features: None,
            expose: true,
            expose_opts: None,
        }
    }

    #[test]
    fn nim_bindings_emit_importc_and_passl() {
        let dir = tempfile::tempdir().unwrap();
        let out = dir.path().join("sha2.nim");
        let exports = vec![
            ExportFn {
                export_name: "sha2_abi_version".into(),
                rust_callee: None,
                params: vec![],
                ret: FfiType::U32,
                kind: ExportKind::Marker,
                is_unsafe: false,
            },
            ExportFn {
                export_name: "sha2_hash_256".into(),
                rust_callee: None,
                params: vec![],
                ret: FfiType::I32,
                kind: ExportKind::Enrichment,
                is_unsafe: false,
            },
        ];
        write_nim_bindings(
            &out,
            "sha2",
            &dep("0.10.9"),
            "sha2_ffi",
            "target/rig/sha2",
            &exports,
        )
        .unwrap();
        let text = std::fs::read_to_string(&out).unwrap();
        assert!(text.contains("proc sha2_abi_version*():"));
        assert!(text.contains("{.passL: \"-lsha2_ffi\".}"));
        assert!(text.contains("{.importc, cdecl.}"));
        assert!(text.contains("sha2_hash_256"));
    }
}
