//! Odin host ← cargo package via generic C ABI façade.

use crate::expose::api_scan::ExportFn;
use crate::expose::surface;
use crate::manifest::Dependency;
use anyhow::{Context, Result};
use std::path::Path;

/// Emit Odin `foreign import` + `foreign` block for the façade cdylib.
pub fn write_odin_bindings(
    out: &Path,
    name: &str,
    dep: &Dependency,
    lib_name: &str,
    native_dir: &str,
    exports: &[ExportFn],
) -> Result<()> {
    let ver = dep.version.as_deref().unwrap_or("*");
    let safe = name.replace('-', "_");
    let mut body = String::new();
    body.push_str(&format!(
        "// Auto-generated by rig for cargo package `{name}` ({ver}).\n\
         // Link search: {native_dir}  lib: {lib_name}\n\
         // Do not edit — regenerate with `rig sync` / `rig add`.\n\
         package {safe}\n\
         \n\
         PACKAGE_NAME :: \"{name}\"\n\
         PACKAGE_VERSION :: \"{ver}\"\n\
         NATIVE_LIB :: \"{lib_name}\"\n\
         NATIVE_DIR :: \"{native_dir}\"\n\
         \n\
         when ODIN_OS == .Windows {{\n\
         \tforeign import rig_lib \"{lib_name}.dll\"\n\
         }} else when ODIN_OS == .Darwin {{\n\
         \tforeign import rig_lib \"{native_dir}/lib{lib_name}.dylib\"\n\
         }} else {{\n\
         \tforeign import rig_lib \"{native_dir}/lib{lib_name}.so\"\n\
         }}\n\
         \n\
         @(default_calling_convention = \"c\")\n\
         foreign rig_lib {{\n"
    ));
    if exports.is_empty() {
        body.push_str(&format!(
            "\t{safe}_abi_version :: proc() -> u32 ---\n\
             \t{safe}_version :: proc() -> cstring ---\n\
             \t{safe}_name :: proc() -> cstring ---\n"
        ));
    } else {
        body.push_str(&surface::emit_odin_foreigns(exports));
    }
    body.push_str("}\n");
    std::fs::write(out, body).with_context(|| format!("write {}", out.display()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::expose::api_scan::{ExportFn, ExportKind, FfiType};
    use crate::manifest::Dependency;

    fn dep(version: &str) -> Dependency {
        Dependency {
            ecosystem: "cargo".into(),
            version: Some(version.into()),
            git: None,
            rev: None,
            path: None,
            url: None,
            features: None,
            default_features: None,
            expose: true,
            expose_opts: None,
        }
    }

    #[test]
    fn odin_bindings_emit_foreign() {
        let dir = tempfile::tempdir().unwrap();
        let out = dir.path().join("sha2.odin");
        let exports = vec![
            ExportFn {
                export_name: "sha2_abi_version".into(),
                rust_callee: None,
                params: vec![],
                ret: FfiType::U32,
                kind: ExportKind::Marker,
                is_unsafe: false,
            },
            ExportFn {
                export_name: "sha2_hash_256".into(),
                rust_callee: None,
                params: vec![],
                ret: FfiType::I32,
                kind: ExportKind::Enrichment,
                is_unsafe: false,
            },
        ];
        write_odin_bindings(
            &out,
            "sha2",
            &dep("0.10.9"),
            "sha2_ffi",
            "target/rig/sha2",
            &exports,
        )
        .unwrap();
        let text = std::fs::read_to_string(&out).unwrap();
        assert!(text.contains("foreign import rig_lib"));
        assert!(text.contains("sha2_abi_version"));
        assert!(text.contains("sha2_hash_256"));
        assert!(text.contains("package sha2"));
    }
}
