//! TypeScript host ← native package via scriptc `--ffi`.
//!
//! A scriptc host is an ordinary TypeScript program: it imports the generated
//! declarations module and scriptc binds those declarations to native symbols
//! and links the archives named in a `--ffi` manifest. There is no in-process
//! ABI façade to write for this host, so the declaration module plus the
//! manifest are the whole contract — and because scriptc takes a single
//! `--ffi` manifest per build, every dependency's manifest is merged into one
//! host-level [`HOST_MANIFEST`].
//!
//! Consumer-mode classes are narrower than a C header: scriptc binds
//! `f64`/`bool`/`u8`/`u32`/`i32`/`void` returns, `f64`/`bool`/`u8`/`u32`/`i32`
//! parameters, and length-delimited `const uint8_t *` + `size_t` spans.
//! Signatures outside that surface are skipped by equilibrium-ffi with a
//! warning rather than mis-bound.

use crate::detect::Language as HostLanguage;
use crate::manifest::Dependency;
use crate::util::AppCtx;
use anyhow::{Context, Result, bail};
use equilibrium_ffi::{GeneratedImport, ImportOptions, generate_imports};
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

/// Host-level `--ffi` manifest binding every exposed dependency.
pub const HOST_MANIFEST: &str = "rig.ffi.json";

/// Write the declarations module for a dependency whose C header and native
/// library are already built (cargo façade, or a path/git library).
pub fn write_ts_bindings(
    out: &Path,
    name: &str,
    dep: &Dependency,
    header: &Path,
    library: &Path,
    manifest_rel: &str,
) -> Result<()> {
    let safe = name.replace('-', "_");
    let own_manifest = format!("{safe}.ffi.json");
    let generated = generate(name, header, library, &own_manifest)?;
    let ver = dep.version.as_deref().unwrap_or("*");
    let body = format!(
        "// Auto-generated by rig for `{name}` ({ver}) — TypeScript host ← native C ABI.\n\
         // Do not edit — regenerate with `rig sync` / `rig add`.\n\
         //\n\
         // scriptc links the native library through the host manifest that rig\n\
         // keeps beside this file:\n\
         //   scriptc build <entry>.ts --ffi {manifest_rel} -o <host>\n\
         // (`rig build <entry>.ts` runs exactly that.)\n\
         {code}",
        code = generated.code
    );
    std::fs::write(out, body).with_context(|| format!("write {}", out.display()))?;
    write_own_manifest(out, &own_manifest, &generated)?;
    report_warnings(name, &generated);
    Ok(())
}

/// Write the declarations module for a path/git dependency, synthesizing the C
/// header equilibrium-ffi parses from the headers (or Zig exports) rig found.
pub fn write_ts_path_native(
    out: &Path,
    name: &str,
    dep: &Dependency,
    built: &crate::expose::path_native::PathNativeBuild,
    manifest_rel: &str,
) -> Result<()> {
    let header = synthesize_header(out, name, dep, built)?;
    write_ts_bindings(out, name, dep, &header, &built.lib_path, manifest_rel)
}

/// Rewrite [`HOST_MANIFEST`] from every exposed dependency's own manifest.
pub fn write_ts_manifest(ctx: &AppCtx) -> Result<()> {
    if ctx.host.language != HostLanguage::TypeScript {
        return Ok(());
    }
    let dir = ctx.root.join(&ctx.manifest.expose.dir);
    let path = dir.join(HOST_MANIFEST);
    let mut functions: Vec<serde_json::Value> = Vec::new();
    let mut libraries: Vec<serde_json::Value> = Vec::new();
    let mut names: BTreeMap<String, String> = BTreeMap::new();

    for (name, dep) in &ctx.manifest.dependencies {
        if !dep.expose {
            continue;
        }
        let safe = name.replace('-', "_");
        let own = dir.join(format!("{safe}.ffi.json"));
        let Ok(text) = std::fs::read_to_string(&own) else {
            // Not exposed in this checkout yet (a fresh `rig add` before
            // `rig sync`); the host has no bindings for it either.
            continue;
        };
        let manifest: serde_json::Value =
            serde_json::from_str(&text).with_context(|| format!("parse {}", own.display()))?;
        for function in manifest["functions"].as_array().into_iter().flatten() {
            let symbol = function["symbol"].as_str().unwrap_or_default().to_string();
            let fname = function["name"].as_str().unwrap_or_default().to_string();
            if let Some(previous) = names.get(&fname) {
                if previous != &symbol {
                    eprintln!(
                        "warn: `{fname}` is declared by two dependencies ({previous} and {symbol}) \
                         — keeping {previous}; give one of them a distinct export name"
                    );
                }
                continue;
            }
            names.insert(fname, symbol);
            functions.push(function.clone());
        }
        for library in manifest["libraries"].as_array().into_iter().flatten() {
            if !libraries.contains(library) {
                libraries.push(library.clone());
            }
        }
    }

    if functions.is_empty() {
        if path.exists() {
            let _ = std::fs::remove_file(&path);
        }
        return Ok(());
    }

    let merged = serde_json::json!({
        "ffi_format": 1,
        "functions": functions,
        "libraries": libraries,
        "system_libraries": [],
    });
    let text = format!("{}\n", serde_json::to_string_pretty(&merged)?);
    std::fs::write(&path, text).with_context(|| format!("write {}", path.display()))?;
    Ok(())
}

fn generate(
    name: &str,
    header: &Path,
    library: &Path,
    manifest_name: &str,
) -> Result<GeneratedImport> {
    let library = absolute(library);
    generate_imports(
        header,
        equilibrium_ffi::Language::ScriptC,
        &ImportOptions::default()
            .native_libraries([library])
            .scriptc_manifest_name(manifest_name),
    )
    .map_err(|err| anyhow::anyhow!("scriptc bindings for `{name}` failed: {err}"))
}

/// scriptc's manifest resolves library paths from the manifest's directory and
/// records them in the linked executable, so hand it an absolute path.
fn absolute(path: &Path) -> PathBuf {
    if path.is_absolute() {
        return path.to_path_buf();
    }
    match std::env::current_dir() {
        Ok(dir) => dir.join(path),
        Err(_) => path.to_path_buf(),
    }
}

fn write_own_manifest(out: &Path, manifest_name: &str, generated: &GeneratedImport) -> Result<()> {
    let Some(companion) = generated
        .companions
        .iter()
        .find(|companion| companion.name == manifest_name)
    else {
        bail!("equilibrium-ffi produced no scriptc `--ffi` manifest named `{manifest_name}`");
    };
    let dir = out.parent().unwrap_or(Path::new("."));
    let path = dir.join(manifest_name);
    std::fs::write(&path, &companion.contents).with_context(|| format!("write {}", path.display()))
}

fn report_warnings(name: &str, generated: &GeneratedImport) {
    for warning in &generated.warnings {
        eprintln!("warn: {name}: {warning}");
    }
}

/// Concatenate the discovered headers into one C header for equilibrium-ffi,
/// falling back to the dep's Zig `export fn` declarations when it ships none.
fn synthesize_header(
    out: &Path,
    name: &str,
    dep: &Dependency,
    built: &crate::expose::path_native::PathNativeBuild,
) -> Result<PathBuf> {
    let mut body = format!(
        "/* Auto-generated by rig — C ABI surface of `{name}` for the TypeScript host. */\n"
    );
    for header in &built.headers {
        let Ok(text) = std::fs::read_to_string(header) else {
            continue;
        };
        body.push_str(&format!("/* {} */\n{text}", header.display()));
        if !text.ends_with('\n') {
            body.push('\n');
        }
    }

    if built.headers.is_empty() && dep.ecosystem == "zig" {
        let exports = crate::expose::zig_export_scan::scan_zig_sources(&built.source_root);
        if !exports.is_empty() {
            body.push_str(&crate::expose::surface::emit_c_decls(&exports));
        }
    }

    if !body.contains(';') {
        bail!(
            "no C header discovered for `{name}` ({}) — a TypeScript host binds through a C \
             header; declare one in the package or expose a cargo package instead",
            dep.ecosystem
        );
    }

    let dir = out.parent().unwrap_or(Path::new("."));
    let path = dir.join(format!("{}.h", name.replace('-', "_")));
    std::fs::write(&path, body).with_context(|| format!("write {}", path.display()))?;
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn dep(ecosystem: &str) -> Dependency {
        Dependency {
            ecosystem: ecosystem.into(),
            version: Some("1.0.0".into()),
            git: None,
            rev: None,
            path: None,
            url: None,
            features: None,
            default_features: None,
            expose: true,
            expose_opts: None,
        }
    }

    #[test]
    fn bindings_and_manifest_land_beside_each_other() {
        let dir = tempfile::tempdir().unwrap();
        let header = dir.path().join("demo.h");
        std::fs::write(&header, "uint32_t demo_add(uint32_t a, uint32_t b);\n").unwrap();
        let library = dir.path().join("libdemo.a");
        std::fs::write(&library, b"!<arch>\n").unwrap();
        let out = dir.path().join("demo.ts");

        write_ts_bindings(
            &out,
            "demo",
            &dep("cargo"),
            &header,
            &library,
            "src/rig_bindings/rig.ffi.json",
        )
        .unwrap();

        let text = std::fs::read_to_string(&out).unwrap();
        assert!(text.contains("export declare function demo_add"));
        assert!(text.contains("--ffi src/rig_bindings/rig.ffi.json"));
        let manifest = std::fs::read_to_string(dir.path().join("demo.ffi.json")).unwrap();
        assert!(manifest.contains("\"symbol\": \"demo_add\""));
        assert!(manifest.contains(&library.display().to_string()));
    }

    #[test]
    fn unsupported_signatures_are_reported_not_bound() {
        let dir = tempfile::tempdir().unwrap();
        let header = dir.path().join("demo.h");
        std::fs::write(
            &header,
            "const char *demo_name(void);\nint64_t demo_big(void);\nint32_t demo_ok(void);\n",
        )
        .unwrap();
        let out = dir.path().join("demo.ts");

        write_ts_bindings(
            &out,
            "demo",
            &dep("cargo"),
            &header,
            &dir.path().join("libdemo.a"),
            "rig.ffi.json",
        )
        .unwrap();

        let text = std::fs::read_to_string(&out).unwrap();
        assert!(text.contains("demo_ok"));
        assert!(!text.contains("demo_name"));
        assert!(!text.contains("demo_big"));
    }
}
