//! V host ← cargo package via generic C ABI façade.

use crate::expose::api_scan::ExportFn;
use crate::expose::surface;
use crate::manifest::Dependency;
use anyhow::{Context, Result};
use std::path::Path;

/// Emit V `#flag` + `fn C.…` declarations for the façade cdylib.
pub fn write_v_bindings(
    out: &Path,
    name: &str,
    dep: &Dependency,
    lib_name: &str,
    native_dir: &str,
    exports: &[ExportFn],
) -> Result<()> {
    let ver = dep.version.as_deref().unwrap_or("*");
    let safe = name.replace('-', "_");
    let mut body = String::new();
    body.push_str(&format!(
        "// Auto-generated by rig for cargo package `{name}` ({ver}).\n\
         // Link search: {native_dir}  lib: {lib_name}\n\
         // Do not edit — regenerate with `rig sync` / `rig add`.\n\
         module {safe}\n\
         \n\
         #flag -L{native_dir}\n\
         #flag -l{lib_name}\n\
         #flag -Wl,-rpath,{native_dir}\n\
         \n"
    ));
    if exports.is_empty() {
        body.push_str(&format!(
            "fn C.{safe}_abi_version() u32\n\
             fn C.{safe}_version() &char\n\
             fn C.{safe}_name() &char\n"
        ));
    } else {
        body.push_str(&surface::emit_v_fns(exports));
    }
    body.push_str(&format!(
        "\n\
         pub const package_name = '{name}'\n\
         pub const package_version = '{ver}'\n\
         pub const native_lib = '{lib_name}'\n\
         pub const native_dir = '{native_dir}'\n\
         \n\
         pub fn abi_version() u32 {{\n\
         \treturn C.{safe}_abi_version()\n\
         }}\n\
         \n\
         pub fn version() string {{\n\
         \treturn unsafe {{ cstring_to_vstring(C.{safe}_version()) }}\n\
         }}\n\
         \n\
         pub fn name() string {{\n\
         \treturn unsafe {{ cstring_to_vstring(C.{safe}_name()) }}\n\
         }}\n"
    ));
    std::fs::write(out, body).with_context(|| format!("write {}", out.display()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::expose::api_scan::{ExportFn, ExportKind, FfiType};
    use crate::manifest::Dependency;

    fn dep(version: &str) -> Dependency {
        Dependency {
            ecosystem: "cargo".into(),
            version: Some(version.into()),
            git: None,
            rev: None,
            path: None,
            url: None,
            features: None,
            default_features: None,
            expose: true,
            expose_opts: None,
        }
    }

    #[test]
    fn v_bindings_emit_flag_and_c_fns() {
        let dir = tempfile::tempdir().unwrap();
        let out = dir.path().join("sha2.v");
        let exports = vec![
            ExportFn {
                export_name: "sha2_abi_version".into(),
                rust_callee: None,
                params: vec![],
                ret: FfiType::U32,
                kind: ExportKind::Marker,
                is_unsafe: false,
            },
            ExportFn {
                export_name: "sha2_hash_256".into(),
                rust_callee: None,
                params: vec![],
                ret: FfiType::I32,
                kind: ExportKind::Enrichment,
                is_unsafe: false,
            },
        ];
        write_v_bindings(&out, "sha2", &dep("0.10.9"), "sha2_ffi", "target/rig/sha2", &exports)
            .unwrap();
        let text = std::fs::read_to_string(&out).unwrap();
        assert!(text.contains("#flag -lsha2_ffi"));
        assert!(text.contains("fn C.sha2_abi_version"));
        assert!(text.contains("sha2_hash_256"));
        assert!(text.contains("module sha2"));
    }
}
