//! V host ← cargo package via generic C ABI façade.

use crate::expose::api_scan::ExportFn;
use crate::expose::surface;
use crate::manifest::Dependency;
use anyhow::{Context, Result};
use std::path::Path;

/// Emit V `#flag` + `fn C.…` declarations for the façade cdylib.
pub fn write_v_bindings(
    out: &Path,
    name: &str,
    dep: &Dependency,
    lib_name: &str,
    native_dir: &str,
    exports: &[ExportFn],
) -> Result<()> {
    let ver = dep.version.as_deref().unwrap_or("*");
    let safe = name.replace('-', "_");
    let mut body = String::new();
    body.push_str(&format!(
        "// Auto-generated by rig for cargo package `{name}` ({ver}).\n// Link search: {native_dir}  lib: {lib_name}\n// Do not edit — regenerate with `rig sync` / `rig add`.\nmodule {safe}\n\n#flag -L{native_dir}\n#flag -l{lib_name}\n#flag -Wl,-rpath,{native_dir}\n#flag -I{native_dir}\n#include \"{lib_name}.h\"\n\n"
    ));
    if exports.is_empty() {
        body.push_str(&format!(
            "fn C.{safe}_abi_version() u32\n\
             fn C.{safe}_version() &char\n\
             fn C.{safe}_name() &char\n"
        ));
    } else {
        body.push_str(&surface::emit_v_fns(exports));
    }
    body.push_str(&format!(
        "\n\
         pub const package_name = '{name}'\n\
         pub const package_version = '{ver}'\n\
         pub const native_lib = '{lib_name}'\n\
         pub const native_dir = '{native_dir}'\n\
         \n\
         pub fn abi_version() u32 {{\n\
         \treturn C.{safe}_abi_version()\n\
         }}\n\
         \n\
         pub fn version() string {{\n\
         \treturn unsafe {{ cstring_to_vstring(C.{safe}_version()) }}\n\
         }}\n\
         \n\
         pub fn name() string {{\n\
         \treturn unsafe {{ cstring_to_vstring(C.{safe}_name()) }}\n\
         }}\n"
    ));
    std::fs::write(out, body).with_context(|| format!("write {}", out.display()))?;
    Ok(())
}

/// Bindings for a built path/git native lib on a V host.
pub fn write_v_path_native(
    out: &Path,
    name: &str,
    dep: &Dependency,
    built: &crate::expose::path_native::PathNativeBuild,
) -> Result<()> {
    let safe = name.replace('-', "_");
    let meta = crate::expose::path_native::path_native_meta_comment(name, dep, built);
    let exports = crate::expose::c_header_scan::scan_headers(&built.headers);
    let mut body = format!(
        "// Auto-generated by rig — {meta}\n// Do not edit — regenerate with `rig sync` / `rig add`.\nmodule {safe}\n\n#flag -L{dir}\n#flag -l{lib}\n#flag -Wl,-rpath,{dir}\n#flag -I{dir}\n\n",
        dir = built.native_rel,
        lib = built.lib_name,
    );
    for h in &built.headers {
        if let Some(fname) = h.file_name().and_then(|s| s.to_str()) {
            body.push_str(&format!("#include \"{fname}\"\n"));
        }
    }
    body.push('\n');
    if exports.is_empty() {
        body.push_str("// No simple C prototypes discovered; declare `fn C.…` as needed.\n");
    } else {
        body.push_str(&surface::emit_v_fns(&exports));
        body.push('\n');
    }
    body.push_str(&format!(
        "pub const package_name = '{name}'\npub const native_lib = '{lib}'\npub const native_dir = '{dir}'\npub const source_root = '{src}'\n",
        lib = built.lib_name,
        dir = built.native_rel,
        src = built.source_root.display(),
    ));
    std::fs::write(out, body).with_context(|| format!("write {}", out.display()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::expose::api_scan::{ExportFn, ExportKind, FfiType};
    use crate::manifest::Dependency;

    fn dep(version: &str) -> Dependency {
        Dependency {
            ecosystem: "cargo".into(),
            version: Some(version.into()),
            git: None,
            rev: None,
            path: None,
            url: None,
            features: None,
            default_features: None,
            expose: true,
            expose_opts: None,
        }
    }

    #[test]
    fn v_bindings_emit_flag_and_c_fns() {
        let dir = tempfile::tempdir().unwrap();
        let out = dir.path().join("sha2.v");
        let exports = vec![
            ExportFn {
                export_name: "sha2_abi_version".into(),
                rust_callee: None,
                params: vec![],
                ret: FfiType::U32,
                ret_adapt: Default::default(),
                kind: ExportKind::Marker,
                is_unsafe: false,
            },
            ExportFn {
                export_name: "sha2_hash_256".into(),
                rust_callee: None,
                params: vec![],
                ret: FfiType::I32,
                ret_adapt: Default::default(),
                kind: ExportKind::Enrichment,
                is_unsafe: false,
            },
        ];
        write_v_bindings(
            &out,
            "sha2",
            &dep("0.10.9"),
            "sha2_ffi",
            "target/rig/sha2",
            &exports,
        )
        .unwrap();
        let text = std::fs::read_to_string(&out).unwrap();
        assert!(text.contains("#flag -lsha2_ffi"));
        assert!(text.contains("fn C.sha2_abi_version"));
        assert!(text.contains("sha2_hash_256"));
        assert!(text.contains("module sha2"));
    }
}
