//! Zig host ← cargo package expose via equilibrium-ffi + C ABI façade.

use crate::expose::api_scan::ExportFn;
use crate::expose::surface;
use crate::manifest::Dependency;
use anyhow::{Context, Result};
use std::path::Path;

/// Write Zig consumer bindings for a built C ABI surface.
pub fn write_zig_bindings(
    out: &Path,
    name: &str,
    dep: &Dependency,
    header: Option<&Path>,
    lib_name: &str,
    native_dir: &str,
    exports: &[ExportFn],
) -> Result<()> {
    let ver = dep.version.as_deref().unwrap_or("*");
    let mut body = String::new();
    body.push_str(&format!(
        "//! Auto-generated by rig for cargo package `{name}` ({ver}).\n\
         //! Linked native lib: `{lib_name}` (search path hint: {native_dir})\n\
         //! Do not edit — regenerate with `rig sync` / `rig add`.\n\n"
    ));

    let mut used_eq = false;
    if let Some(header) = header
        && header.is_file()
    {
        match equilibrium_ffi::generate_imports(
            header,
            equilibrium_ffi::Language::Zig,
            &equilibrium_ffi::ImportOptions::default(),
        ) {
            Ok(generated) => {
                used_eq = true;
                body.push_str(
                    "// --- equilibrium-ffi generate_imports (commented provenance) ---\n",
                );
                for line in generated.code.lines() {
                    body.push_str("// ");
                    body.push_str(line);
                    body.push('\n');
                }
                for w in &generated.warnings {
                    body.push_str(&format!("// warning: {w}\n"));
                }
                body.push('\n');
            }
            Err(err) => {
                body.push_str(&format!(
                    "// equilibrium-ffi generate_imports failed: {err}\n\n"
                ));
            }
        }
    }

    body.push_str("// --- portable extern \"c\" (canonical façade) ---\n");
    if exports.is_empty() {
        let safe = name.replace('-', "_");
        body.push_str(&format!(
            "pub extern \"c\" fn {safe}_abi_version() u32;\n\
             pub extern \"c\" fn {safe}_version() [*:0]const u8;\n\
             pub extern \"c\" fn {safe}_name() [*:0]const u8;\n"
        ));
    } else {
        body.push_str(&surface::emit_zig_externs(exports));
    }
    body.push_str(&format!(
        "\npub const package_name = \"{name}\";\n\
         pub const package_version = \"{ver}\";\n\
         pub const native_lib = \"{lib_name}\";\n\
         pub const used_equilibrium_ffi = {};\n",
        if used_eq { "true" } else { "false" }
    ));

    std::fs::write(out, body).with_context(|| format!("write {}", out.display()))?;
    Ok(())
}
