use crate::manifest::Dependency;
use anyhow::{Context, Result};
use std::path::Path;

/// Generate a Zig consumer stub. Full equilibrium_ffi::generate_imports runs when
/// a C header is available under target/rig/<pkg>; until then we ship a compiling
/// stub that documents the link path and `@import` surface.
pub fn write_zig_bindings_stub(out: &Path, name: &str, dep: &Dependency) -> Result<()> {
    let ver = dep.version.as_deref().unwrap_or("*");
    let native = dep
        .expose_opts
        .as_ref()
        .and_then(|o| o.native.clone())
        .unwrap_or_else(|| format!("target/rig/{name}"));
    let body = format!(
        r#"//! Auto-generated by rig for cargo package `{name}` ({ver}).
//! Replace/extend when equilibrium-ffi generate_imports has a C header.
//! Native artifact hint: {native}
const std = @import("std");

pub const package_name = "{name}";
pub const package_version = "{ver}";

/// Placeholder until cdylib + header are produced under {native}.
pub export fn rig_{safe}_version() [*:0]const u8 {{
    return "{ver}";
}}
"#,
        safe = name.replace('-', "_"),
    );
    std::fs::write(out, body).with_context(|| format!("write {}", out.display()))?;
    Ok(())
}
