use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::path::Path;

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct Lockfile {
    #[serde(default = "one")]
    pub schema_version: u32,
    #[serde(default)]
    pub package: Vec<LockedPackage>,
}

fn one() -> u32 {
    1
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LockedPackage {
    pub name: String,
    pub ecosystem: String,
    pub version: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub checksum: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub features: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expose_consumer: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expose_out: Option<String>,
}

impl Lockfile {
    pub fn load(path: &Path) -> Result<Self> {
        let text =
            std::fs::read_to_string(path).with_context(|| format!("read {}", path.display()))?;
        toml::from_str(&text).context("parse rig.lock")
    }

    pub fn save(&self, path: &Path) -> Result<()> {
        let text = toml::to_string_pretty(self).context("serialize rig.lock")?;
        let header = "# This file is automatically @generated by rig.\n# It is not intended for manual editing.\n";
        std::fs::write(path, format!("{header}{text}"))
            .with_context(|| format!("write {}", path.display()))?;
        Ok(())
    }

    pub fn upsert(&mut self, pkg: LockedPackage) {
        if let Some(existing) = self.package.iter_mut().find(|p| p.name == pkg.name) {
            *existing = pkg;
        } else {
            self.package.push(pkg);
        }
        self.package.sort_by(|a, b| a.name.cmp(&b.name));
    }

    pub fn remove(&mut self, name: &str) -> bool {
        let before = self.package.len();
        self.package.retain(|p| p.name != name);
        before != self.package.len()
    }
}
